
load("//tensorflow:tensorflow.bzl", "tf_custom_op_library")

tf_custom_op_library(
    name = "matrixlstm_helpers.so",
    srcs = ["matrixlstm_helpers.cc"],
    gpu_srcs = ["matrixlstm_helpers.cu.cc"],
)
